// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZNJPMVOK6RGRPCw68YP9btLs3_rDwlJ0',
    appId: '1:61651401056:web:ea305eb57689c19fbb8605',
    messagingSenderId: '61651401056',
    projectId: 'quiz-app-ff430',
    authDomain: 'quiz-app-ff430.firebaseapp.com',
    storageBucket: 'quiz-app-ff430.appspot.com',
    measurementId: 'G-3Q2M9GNZDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDokHwL1QbzQlAX4ZbgOSuuytlJF_twhWM',
    appId: '1:61651401056:android:859be75778cfceeabb8605',
    messagingSenderId: '61651401056',
    projectId: 'quiz-app-ff430',
    storageBucket: 'quiz-app-ff430.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSVeM201Y1h9QTfr8pAKZC7T2NqlyXB7Y',
    appId: '1:61651401056:ios:5d9e7067b56cfcfbbb8605',
    messagingSenderId: '61651401056',
    projectId: 'quiz-app-ff430',
    storageBucket: 'quiz-app-ff430.appspot.com',
    androidClientId: '61651401056-fd19qa9uvbrmi40ui8kefo2nhs36gagj.apps.googleusercontent.com',
    iosClientId: '61651401056-c4f3bnnfq2v93hqbqssfv08amjank7h8.apps.googleusercontent.com',
    iosBundleId: 'io.pjt.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSVeM201Y1h9QTfr8pAKZC7T2NqlyXB7Y',
    appId: '1:61651401056:ios:4e5691e492418c79bb8605',
    messagingSenderId: '61651401056',
    projectId: 'quiz-app-ff430',
    storageBucket: 'quiz-app-ff430.appspot.com',
    androidClientId: '61651401056-fd19qa9uvbrmi40ui8kefo2nhs36gagj.apps.googleusercontent.com',
    iosClientId: '61651401056-q3n6k4n9nqrstt9g0pn6o4p24fkftgvm.apps.googleusercontent.com',
    iosBundleId: 'io.pjt.quizapp.RunnerTests',
  );
}
